Ansible 1
Otus-DevOps-2018-05/kumite73_infra pull request #10
Opened 2018-07-04 20:45 UTC by kumite73

# Выполнено ДЗ №

 - [X] Основное ДЗ
 - [X] Задание со *

## В процессе сделано:
Устанавливаем ansible

    easy_install `cat requirements.txt`

Проверяем версию `ansible --version` результат `ansible 2.6.0`
Добавляем `output` переменную для терраформа в модуль `db`

    output "db_external_ip" {
        value = "${google_compute_instance.db.network_interface.0.access_config.0.assigned_nat_ip}"
    }

Добавляем `output` переменную для терраформа в `stage and production`

    output "db_external_ip" {
        value = "${module.db.db_external_ip}"
    }

Создаем `inventory`

    appserver ansible_host=35.195.178.52 ansible_user=appuser ansible_private_key_file=~/.ssh/appuser

Добавляем в `inventory`

    dbserver ansible_host=35.240.108.228 ansible_user=appuser ansible_private_key_file=~/.ssh/appuser

Вызоваем модуль ping `ansible dbserver -i ./inventory -m ping`
Создаем `ansible.cfg`

    [defaults]
    inventory = ./inventory
    remote_user = appuser
    private_key_file = ~/.ssh/appuser
    host_key_checking = False
    retry_files_enabled = False

Удаляем избыточную информацию в `inventory`
Создаем группы хостов в `inventory`

    [app]
        appserver ansible_host=35.195.178.52
    [db]
        dbserver ansible_host=35.240.108.228

Создаем `inventory.yml`

    app:
      hosts:
        appserver:
          ansible_host: 35.195.178.52
    db:
      hosts:
        dbserver:
          ansible_host: 35.240.108.228

Проверияем, что на app сервере установлены компоненты для работы

    ansible app -m command -a 'ruby -v'
    ansible app -m command -a 'bundler -v'

А вот здесь ошибка

    ansible app -m command -a 'ruby -v; bundler -v'

Меняем модуль на `shell`

    ansible app -m shell -a 'ruby -v; bundler -v'

Проверяем `MongoDB`

    ansible db -m command -a 'systemctl status mongod'

Или с помощью `systemd`

    ansible db -m systemd -a name=mongod

Или с `service`

    ansible db -m service -a name=mongod

Клонируем репо

    ansible app -m git -a 'repo=https://github.com/express42/reddit.git dest=/home/appuser/reddit'

Создаем playbook `clone.yml`

    ---
    - name: Clone
      hosts: app
      tasks:
        - name: Clone repo
            git:
            repo: https://github.com/express42/reddit.git
            dest: /home/appuser/reddit

Выполняем: `ansible-playbook clone.yml`
Выполняем: `ansible app -m command -a 'rm -rf ~/reddit'`
Выполняем: `ansible-playbook clone.yml`
Если задача ансибла ничего не меняет - то выводится статус Ok. Так-как мы удалили данные, то задача вернула статус Changed так-как произошло клонирование репозитория, который раньше был уже скопирован.

### Ansible-1 *
Создан файл `inventory.json`
Создан файл `inventory.rb`

    #!/usr/bin/env ruby
    # encoding: UTF-8

    require 'open3'
    require 'json'

    $VERBOSE=nil

    begin
        app_ip, status = Open3.capture3("cd ../terraform/stage; terraform output app_external_ip;")
        db_ip, status = Open3.capture3("cd ../terraform/stage; terraform output db_external_ip;")
        if ARGV[0] == '--list'
            j = {app: {hosts: [app_ip.strip]}, db: {hosts: [db_ip.strip]},'_meta' => {'hostvars': {}}}
        else
            j = {app: {hosts: {appserver: {ansible_host: app_ip.strip}}}, db: {hosts: {dbserver: {ansible_host: db_ip.strip}}},'_meta' => {'hostvars': {}}}
        end
        puts JSON.pretty_generate(j)
    rescue
        puts 'Error'
    end

Выдаем права на запуск `chmod +x inventory.rb`
Результат работы `ansible all -i ./inventory.rb -m ping`

    35.240.108.228 | SUCCESS => {
        "changed": false,
        "ping": "pong"
    }
    35.195.178.52 | SUCCESS => {
        "changed": false,
        "ping": "pong"
    }

Результат генерации полного `inventory` запуск  `./inventory.rb`

    {
        "app": {
            "hosts": {
                "appserver": {
                    "ansible_host": "35.195.178.52"
                }
            }
        },
        "db": {
            "hosts": {
                "dbserver": {
                    "ansible_host": "35.240.108.228"
                }
            }
        },
        "_meta": {
            "hostvars": {
            }
        }
    }

Меняем строчку в `ansible.cfg`

    inventory = ./inventory

На

    inventory = ./inventory.rb

Запускаем `ansible all -m ping`
Результат

    35.240.108.228 | SUCCESS => {
        "changed": false,
        "ping": "pong"
    }
    35.195.178.52 | SUCCESS => {
        "changed": false,
        "ping": "pong"
    }

## PR checklist
 - [ansible-1] Выставил label с номером домашнего задания
 - [Ansible] Выставил label с темой домашнего задания

2018-07-13 17:34 UTC, Nklya requested changes
Добрый вечер.

Алексей, в этом PR должно быть только то, что выполняется в этом ДЗ.
А сейчас здесь и следующее.
<img width="376" alt="image" src="https://user-images.githubusercontent.com/26086394/42705419-ecbef4cc-86db-11e8-8f54-9ea5b43583c0.png">

2018-07-14 16:35 UTC, kumite73 commented
Удалил файлы из дз Ansible-2

2018-07-16 15:48 UTC, Nklya approved these changes
Добрый вечер.

Алексей, теперь все отлично 👍

2018-07-16 15:48 UTC, Nklya commented on ansible/=2.4
> +Downloading/unpacking ansible
Я не думаю, что это здесь нужно

2018-07-16 15:48 UTC, Nklya commented on ansible/inventory.rb
> +  app_ip, stderr_str, status = Open3.capture3("cd ../terraform/stage; terraform output app_external_ip;")
stage лучше задавать в качестве параметра,. чтобы скрипт был универсальный для разных путей.

2018-07-16 15:48 UTC, Nklya commented on ansible/inventory.rb
> +  if ARGV[0] == '--list'
Скрипт прикольный  👍

2018-07-16 15:49 UTC, Nklya commented
Сейчас нужно смежить этот PR и подмержить мастер в следущий PR

2018-07-16 23:32 UTC, merged